### ISSUE TITLE
[Feature Request] Pull Information from Actors

### ISSUE THREAD

**Issue by GhostwheelX** [CristianVasile23/conversation-hud#12]
Might it be possible to reference existing actors to pull their portrait and name instead of having to insert the name and picture manually?

Bonus points for being able to select multiple actors at a time.

**Comment by CristianVasile23** [comment]
You can reference actors by dragging and dropping them onto an already active conversation, the conversation input form, or even a saved conversation. When you start dragging an actor you will see an area on which you can drop the actor to add them to the conversation (you can also drag & drop other items such as saved conversations or journal entries that contain pages that are of image type).

As to referencing multiple actors at a time, at the moment you can't really do that but I have plans to add support for folders as well so you can drag a folder with multiple actors to add them all.

Unless I am mistaken, this should be pretty much you requested, no? Or is there another way you would like to do this referencing?

**Comment by GhostwheelX** [comment]
Ah, I hadn't realized that was possible, thank you 🙂
