### ISSUE TITLE
[Feature Suggestion] Re-order Actors

### ISSUE THREAD

**Issue by GhostwheelX** [CristianVasile23/conversation-hud#14]
Might it be possible to allow the GM to drag actors up and down and re-order the order in which they show up?

**Comment by CristianVasile23** [comment]
That is a planned feature. I think it's useful to have and I want to have that in my games as well so I will be adding it in an upcoming version of the module. That said, It might take some time as I am a bit busy at the moment, but it is coming.

**Comment by CristianVasile23** [comment]
The option to reorder participants is now available in 4.1.0 by dragging and dropping (in the future I might also add some buttons for that, but for now drag and drop should suffice).

If you encounter any issues, feel free to contact me (here or on discord) and I will try to solve them.

As to the faction separator (#13), that is in the works and should come with the next major release of the module (most likely sometime towards the end of this month).
