### ISSUE TITLE
[Bug] CSS image alignment

### ISSUE THREAD

**Issue by Dispositif** [CristianVasile23/conversation-hud#17]
With an image in portrait format, the active character's image is incorrectly aligned.
See example with 523x1000px image : https://zupimages.net/up/23/25/bk6d.jpg

**Comment by CristianVasile23** [comment]
Hey there, thanks for letting me know, I will look into it.

A fix should be available at the start of next week or maybe even tomorrow as I have been reworking a lot of the code and fixing several issues. I will see if this bug still happens in the upcoming version of the module, and if so, I will fix it.

**Comment by CristianVasile23** [comment]
With version 5.0.1, I have added a fix to the bug you have found. That said, the active portrait behaved correctly, it was the smaller thumbnail that wasn't working properly.

By default, the portraits have their anchor set in the center, if you want to display them from the top to the bottom (as is the case for the picture you have provided), you have to go into the module settings and set the portrait anchor to _Top_.

For now, this setting is for all images, but I have plans to add the option to set the anchor position individually for each participant (for now, you can bypass this limitation by manually cropping the images that display incorrectly).

If you have any questions or issues, please do not hesitate to reach out.

**Comment by CristianVasile23** [comment]
Hey again, I appreciate the feedback, one of the goals was to make the module easy to use and somewhat intuitive, so I am glad to hear that you found it that way.

Regarding the anchor option, if most people do not use it's whatever, the important thing is to at least have an option and more control over the display. The feature itself is going to be optional, by default the images will use the global setting, and if you need a specific image to be anchored differently, you can set it in the participant config. The goal is to give users flexibility.
