### ISSUE TITLE
Allow the conversation editor to select "starting speaker"

### ISSUE THREAD

**Issue by TheSabotender** [CristianVasile23/conversation-hud#23]
![image](https://github.com/CristianVasile23/conversation-hud/assets/12509732/cba30f87-6a87-4040-b80b-068ec0ff7665)
![image](https://github.com/CristianVasile23/conversation-hud/assets/12509732/0660a1bc-5925-4e14-87f9-8ab775bbd732)

When editing a new (or saved) conversation, i should be able to select which participant starts selected. To avoid the players seeing the "No active participant" box.

**Comment by CristianVasile23** [comment]
Hey there, this feature was also something that I wanted to implement as I felt it was sorely needed in some cases and I am pleased to announce that it's already done and will be coming with the next version of this module which will be releasing sometime during the first half of the next month.

In the meantime, I will leave the issue open until the new version is released.

**Comment by CristianVasile23** [comment]
Hey, so with release 5.1.0 you can now select which participant should be active by default by using the checkboxes present for each participant. The UI looks like this now:
![1](https://github.com/CristianVasile23/conversation-hud/assets/51834117/eca6bf46-7ca2-40d2-8ad1-b800f43bfd7d)

If you have any other questions or requests, feel free to contact me and I will do my best to solve them.
