### ISSUE TITLE
Add an "End Conversation" button

### ISSUE THREAD

**Issue by TheSabotender** [CristianVasile23/conversation-hud#24]
![image](https://github.com/CristianVasile23/conversation-hud/assets/12509732/8f90a4f9-4c98-42ec-b127-cc593b89d52b)
When a conversation is active, it would be nice to have an "End conversation" button together with the conversation controls.

**Comment by CristianVasile23** [comment]
That's a good suggestion, closing an active conversation was a bit annoying I will admit. Adding a close button to the controls should be easy enough, I will get on that as well.

**Comment by CristianVasile23** [comment]
I have added the button with release 5.1.0, this should make closing conversation much easier. Once more, if there is anything else  feel free to reach out.
