### ISSUE TITLE
[Feature Request] Add Easy Way to Duplicate Factions

### ISSUE THREAD

**Issue by kiligir** [CristianVasile23/conversation-hud#28]
I might be missing it, but manually setting banners for everyone in a 15-person conversation is a lot. If there isn't already a way to do this, a drag-and-drop functionality or library of factions and banner setups would be amazing.

**Comment by CristianVasile23** [comment]
Hey there,
You are right that currently there is no way to clone/save factions and you have to recreate them manually for each participant. This is a known issue and I am thinking of a way to handle this limitation, I have some ideas in mind but nothing concrete as of this moment. This feature is pretty high up on my list of things that need to be implemented, however I think that this feature will arrive in the first couple of months of 2024 as currently I am focusing on writing the wiki for the module.

As a really weak band-aid fix, I have added the option to clone already existing participants which can help in reducing the time needed to create a factions as cloning them will already have the factions properly created and you only need  to edit the portrait and name of the participant. It's not ideal I know, but it's the only thing at the moment.

**Comment by CristianVasile23** [comment]
I am happy to tell you that with release 5.3.0 you can now finally save factions into their respective sheets and then assign them to conversation participants. No more having to manually recreate a faction for every participant, you can now just export an already created faction and re-assign it to everyone else.

If you find any issues or have any questions, feel free to contact me and I will do my best to help.

**Comment by kiligir** [comment]
This is amazing, and your efforts are appreciated! Saw it in the changelog and was bit with a bolt of joy. Thank you!
