### ISSUE TITLE
Speak As Issue

### ISSUE THREAD

**Issue by XXDarrienX** [CristianVasile23/conversation-hud#29]
I do not know if I am using it wrong but I do have speak as and it is turned on but typing in chat for the npc just puts it in the roll channel, when I hide the conversation, I am able to speak as the NPC normally. Not sure whatever information you need.

**Comment by CristianVasile23** [comment]
Hi there and sorry for the somewhat late reply.

This is most likely an incompatibility with another module that you are using. As far as I know, in the default application there are no separate channels for rolls or messages, it's just the chat tab and when I added the _Speak As_ functionality I made it work only for the vanilla chat behavior.

I can look into the issue and try to make the module work with the channels as well, but I will need to know what module you are using for the channels so that I test locally and make CHUD compatible with it.

Thanks!

**Comment by XXDarrienX** [comment]
Here is my active mod list

Active Modules:
----------
5e - Custom Abilities & Skills v;
About Time v;
Active Auras v;
Active Token Effects v;
Add a Resource v;
Advantage Reminder for dnd5e v;
Always HP v;
Anonymous v;
Argon - Combat HUD (CORE) v;
Argon - Combat HUD (DND5E) v;
Arms Reach v;
Automated Animations v;
Automated Conditions 5e v;
Automated Evocations - Companion Manager v;
Backpack Manager v;
Beaver's Crafting Module v;
Beaver's Potions v;
Beaver's System Adaption dnd5e v;
Beaver's System Interface v;
Better Roofs v;
Build-a-Bonus v;
Caeora's Maps, Tokens, and Assets v;
Carousel Combat Tracker v;
Chat Commander v;
Chibbin Grove Free Compendium v;
Combat Booster: Turn Marker, Recent Actions and more v;
Compendium Folders v;
ConversationHUD v;
Cozy Maps - Free v;
Cursor Hider v;
Czepeku Sci-Fi - Arctic Institute v;
Czepeku Sci-Fi - Cyberpunk Streets v;
Czepeku Sci-Fi - Decimator Mech Depot v;
Czepeku Sci-Fi - Magnus Starship Part 1 v;
Damage Log v;
D&D5e Animations v;
D&D5e Character Monitor v;
DF Curvy Walls v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice Tray v;
Dig Down - Advanced Search v;
DnD5e Drag Ruler Integration v;
DND5E Scriplets - 5E QOL bits and pieces v;
Domille's Wondrous Works - Battlemap Collection v;
Drag Ruler v;
Dungeon Draw v;
Dynamic effects using Active Effects (DAE) v;
Easy Exports v;
Effect Macro v;
Filepicker Improvements v;
Forien's Copy Environment v;
Foundry Community Macros v;
Foundry Community Tables v;
GM Notes v;
GM Screen v;
Grid Scaler v;
Health Estimate v;
Hey, Wait! v;
Hyperdrive Fleet - Animated Acorn Explorer v;
Hyperdrive Fleet - Animated Albatross - Long Range Explorer v;
Hyperdrive Fleet - Animated Asteria - Luxury Space Yacht v;
Hyperdrive Fleet - Animated Blue Swallow - Recon Vessel v;
Hyperdrive Fleet - Animated Cargo Camel v;
Hyperdrive Fleet - Animated Claymore Carrier v;
Hyperdrive Fleet - Animated Enlightener - Hell Frigate v;
Hyperdrive Fleet - Odobenus - Prison Transport v;
Hyperdrive Fleet - Sample Pack v;
Hyperlanes v;
Illandril's Inventory Sorter (5e) v;
Image Previewer v;
Item Collection\Item Container for Dnd5e v;
Item Macro v;
Item Piles v;
Items with Spells DnD5e v;
Jack Kerouac's Animated Spell Effects v;
Jack Kerouac's Animated Spell Effects: Cartoon v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Jinker's Animated Art Pack v;
Levels v;
lib - Color Settings v;
Lib: Document Sheet Registrar v;
Library: DF Module Buttons v;
Library - Find the Path v;
libWrapper v;
Limits v;
Lock & Key v;
Loot Sheet NPC 5e (Simple Version) v;
Macro Grid v;
Map Doctor: Free Bundle v;
Mass Edit v;
Math.js v;
Melvin's Mechanical Masterworks v;
Midi QOL v;
Midi SRD v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Chat Timer v;
Monk's Combat Details v;
Monk's Enhanced Journal v;
Monk's Enhanced Journal Objectives styles v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's Shops v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Multilevel Tokens v;
Multiple Document Selection v;
Note Licker v;
Not Your Turn! v;
Party Inventory v;
Party Resources v;
Patrol v;
Pin Cushion v;
Pings v;
Polyglot v;
Pull Players to Scene v;
Quick Grid Align v;
Quick Insert - Search Widget v;
Random Procedural Core v;
Random Procedural Creations v;
Random Procedural Names v;
Rest Recovery for 5E v;
Rideable v;
Roll Table from Sidebar and Journal v;
routinglib v;
Rush - Mob Movement v;
Sequencer v;
Settings Extender v;
Simbul's Athenaeum v;
Simbul's Cover Calculator v;
Simbul's Creature Aide v;
Simple Calendar v;
Skill Customization for D&D5e v;
SmallTime v;
Smart Target v;
socketlib v;
SoundFx Library v;
Speak As…… v;
Spellarena Battlemap Collection v;
Status Halo v;
Stealthy v;
Tabbed Chatlog v;
Tagger v;
Tasteful Tooltips v;
Template Macro v;
Terrain Mapper v;
The Forge v;
The Forge: More Awesomeness v;
Tidy5e Sheet v;
Tidy 5e Sheets Kgar Alpha v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD Core v;
Token Action HUD D&D 5e v;
Tokenizer v;
Token Light Condition v;
Token Magic FX v;
Token Says v;
Token Warp v;
Torch v;
Universal Animations v;
User Latency v;
Variant Encumbrance+Midi v;
Vision 5e v;
Visual Active Effects v;
Walled Templates v;
Wall Height v;
Warp Gate v;
World Scripter v;

Inactive Modules:
----------
5e-Sheet Resources Plus v;
5e Statblock Importer v;
Abomination Vaults maps remake v;
Advanced Macros v;
Agents of Edgewatch maps remake v;
Angela Maps - Free Map Pack v;
Baileywiki Free Maps Pack v;
Chris's Premades v;
Custom Character Sheet Sections v;
Darkraven Games Free Fantasy and Sci-Fi Soundscapes v;
DF Active Lights v;
Domille's Wondrous Works Free Phased Battle Maps v;
Domille's wondrous works - Scene Phaser (Free version) v;
Drag Upload (Get Over Here!) v;
Drehatlas' Maps v;
Elevenlabs for Foundry v;
Elven Tower Free Maps v;
Emojify v;
Extinction Curse maps remake v;
Fall of Plaguestone maps remake v;
Find the culprit v;
Forgotten Adventures Battlemaps v;
Frag Maps - Modern, Cyberpunk and Sci-Fi Maps v;
HoloGrounds Free Maps v;
Hyperdrive Fleet - Abyssal - Deep Sea Ship v;
Hyperdrive Fleet - Alien Mothership v;
Hyperdrive Fleet - Ancient World Forge v;
Hyperdrive Fleet - Aniamted Macrocheira - Repair Ship v;
Hyperdrive Fleet - Animated Abyssal - Deep Sea Ship v;
Hyperdrive Fleet - Animated Ancient World Forge v;
Hyperdrive Fleet - Animated Cassowary Shield Guardian v;
Hyperdrive Fleet - Animated Crystal Mines v;
Hyperdrive Fleet - Animated Dragonette Star Racer v;
Hyperdrive Fleet - Animated Dynamo Bomber v;
Hyperdrive Fleet - Animated Extraction Point v;
Hyperdrive Fleet - Animated Exuvidax - Alien Cannon v;
Hyperdrive Fleet - Animated Hoopoe - Cargo Ship v;
Hyperdrive Fleet - Animated Husk Gnome Scythe v;
Hyperdrive Fleet - Animated Megaimperax - Alien Carrier v;
Hyperdrive Fleet - Animated Odyssey 12 - Terraformer v;
Hyperdrive Fleet - Animated Orbital Defence Cannon v;
Hyperdrive Fleet - Animated Ouroboros Part 2 v;
Hyperdrive Fleet - Animated Planatus - Bio-dome Research Vessel v;
Hyperdrive Fleet - Animated Prime Mover v;
Hyperdrive Fleet - Animated Razorbill - Interceptor v;
Hyperdrive Fleet - Animated Reactor Core v;
Hyperdrive Fleet - Animated Squengi's Grill v;
Hyperdrive Fleet - Animated - Urraca - Merchant Ship v;
Hyperdrive Fleet - Animated Zone 51 v;
Hyperdrive Fleet - Anura - Walker v;
Hyperdrive Fleet - Apocalyptic Fuel Station v;
Hyperdrive Fleet - Asteria - Luxury Space Yacht v;
Hyperdrive Fleet - Barracuda - Destroyer v;
Hyperdrive Fleet - Caladrius - Medical Ship v;
Hyperdrive Fleet - Canadensis - Blockade Runner v;
Hyperdrive Fleet - Cassowary v;
Hyperdrive Fleet - Crystal Mines v;
Hyperdrive Fleet - Cyberpunk Streets v;
Hyperdrive Fleet - Delphadox - Alien Navigator v;
Hyperdrive Fleet - Eversor v;
Hyperdrive Fleet - Hawkeye - Bounty Hunter v;
Hyperdrive Fleet - Hoopoe - Cargo Ship v;
Hyperdrive Fleet - Horus 918 - Far Portal v;
Hyperdrive Fleet - HWSS Empress v;
Hyperdrive Fleet - Leiothrix - Boarding Ship v;
Hyperdrive Fleet - Macrocheira - Repair Ship v;
Hyperdrive Fleet - Mavel III - Junk Bucket v;
Hyperdrive Fleet - Megaimperax - Alien Carrier v;
Hyperdrive Fleet - Odyssey 12 - Terraformer v;
Hyperdrive Fleet - Orbital Defence Cannon v;
Hyperdrive Fleet - Ouroboros v;
Hyperdrive Fleet - Ouroboros v;
Hyperdrive Fleet - Ouroboros Part 2 v;
Hyperdrive Fleet - Ouroboros Part 3 v;
Hyperdrive Fleet - Prime Mover v;
Hyperdrive Fleet - Reactor Core v;
Hyperdrive Fleet - Tettigarctidax - Fighter Ship v;
Hyperdrive Fleet - The Claymore Carrier v;
Hyperdrive Fleet - The Enlightener - Hell Frigate v;
Hyperdrive Fleet - Zone 51 v;
Icon Picker v;
Ironfang Invasion Maps Remake v;
Kanka-Foundry v;
Kobold DM Kingmaker Maps (Remakes) v;
Koboldworks – Data Inspector 🔍 v;
Lancer Weapon FX v;
Malevolence Reimagined Maps by Narchy v;
Mark Drummond J - Free Pack v;
Mark's Mark of the Mantis Maps v;
Maxwell's Manual of Malicious Maladies v;
MikWewa Free Maps v;
Milby's Maps Free v;
Miska's Maps - Battlemaps - Starter Pack v;
Monk's Common Display v;
Monk's Hotbar Expansion v;
Moonlight Maps v;
Multiface Tiles v;
Narrator Tools v;
Night of the Gray Death Maps Remake v;
PF2e QftFF Maps v;
Revised Weapons & Equipment v;
Rise of the Runelords Maps by Narchy v;
RuinWorks Free Content v;
Sound of Token v;
Stat Drawer v;
Super's Homebrew Compendium v;
Swarms v;
Tabletop RPG Music v;
TacticalMap Battlemaps v;
The Reclusive Cartographer | Free Foundry Content v;
TheRipper93's Module Hub v;
Token Attacher v;
Token Mirror Button v;
Token Variant Art v;
Troubles in Otari maps remake v;
Vehicle Tokens v;
WFRP4E - Fan-made maps for Death on the Reik v;
WFRP4E - Fan-made maps for Ennemy in Shadows v;
WFRP4E - Fan-made maps for Power Behind The Throne v;
WFRP4E - Fan-made maps for Ubersreik and its area v;
WTF: What the Flag? v;

**Comment by CristianVasile23** [comment]
I have fixed the issue you described in the 5.3.0 version of the module. I haven't checked every module on your list, but it appeared that the issue was only with the _Tabbed Chatlog_ module. The _Speak As_ feature should now work accordingly.

If you have any other issues or questions, feel free to contact me and I will help as best as I can.
