### ISSUE TITLE
[SUGGESTION] - Add the option to drag-drop existing actors to the conversation

### ISSUE THREAD

**Issue by Ikabodo** [CristianVasile23/conversation-hud#3]
It's nice to just be able to add images and a name, but in many cases you already have an actor ready. In these cases it would be nice to just be able to drag and drop and actor to the ui. It then takes the actor image and the name and adds them.

**Comment by CristianVasile23** [comment]
The drag and drop feature has been added with release 3.3.0.
If I have missed something please do tell me, otherwise I will be closing the issue in a day.
