### ISSUE TITLE
[Feature Request] Button to add all (visible) NPC's from current scene to the HUD?

### ISSUE THREAD

**Issue by serbandr** [CristianVasile23/conversation-hud#30]
I feel like such a feature would make it easier and faster to get the HUD going rather than having to check who's there, and 1 by 1 look them up in the actors directory to drag and drop them. It could just be a button next to 'Add Participant' called 'Pull Participants From Scene' or something along those lines. Would that be possible to implement?

**Comment by CristianVasile23** [comment]
That sounds like a good idea and it shouldn't be too hard to add. I will try to add this feature in the upcoming release.

**Comment by CristianVasile23** [comment]
With release 5.3.0 I have added an additional button that pulls all actors from the currently viewed scene.

The only mention that I have is that it pulls both PCs and NPCs, differentiating between the two would have been problematic and there might be cases were one would want to add PCs into a conversation, as such, what happens now is that once you click a dialogue an additional sheet appears were you can select which actors to include into the conversation. By default, all the visible actors are selected, but you can even add the ones that are hidden should you wish to.

If you have any questions or issues regarding this feature or the module, feel free to reach out and I will do my best to help.
