### ISSUE TITLE
[Feature Request] Option to make only the talking NPC visble No side bar for Players

### ISSUE THREAD

**Issue by AxiumDND** [CristianVasile23/conversation-hud#31]
Now that Monks common display has been updated I can finialy use this module. So far it works great.

One thing for the way I use it would be the list of NPC's for selection I dont need that for My players to see so in the config page a turn this off for players would be useful. 

keep up the good work. 

Axium

**Comment by CristianVasile23** [comment]
A toggle in the config shouldn't be too hard to add and it allows for more flexibility, I will try to add it in the next release.

**Comment by AxiumDND** [comment]
That's great news and thankyou for all your hard work this has been an excellent addition to my games.

**Comment by CristianVasile23** [comment]
As per your request, with release 5.3.0 I have added an extra toggle in the module settings (_Display Participants List_) which allows you to enable or disable the list of participants for the players.

If you have any issues or questions, feel free to reach out and I will answer as soon as possible!
