### ISSUE TITLE
[Feature Request] option to alter or remove the background blur

### ISSUE THREAD

**Issue by DiceKnights** [CristianVasile23/conversation-hud#34]
Either a check box to remove entirely, or even better a slider to adjust background blur when the HUD is active.

Firstly, the blur is FANTASTIC idea when using it on a map screen, as it really brings focus to the conversation rather people fidgeting moving tokens on the map. 

However, I find it isn't as desirable on a theatre of mind scene.  For example when in a safer location such as a town I'll generally switch to full screen images of say.. the interior of an inn or temple.. just to set the mood since combat is less likely to occur.  I'd love for that to still be visible while the HUD is open.

Thanks,
Shane

**Comment by CristianVasile23** [comment]
I can definitely add some customization options for the blur amount, I think that's a pretty good idea and it gives users flexibility, so I will look into that.

Furthermore, I think I can add a button in the conversation controls that toggles the blur on or off, should be pretty easy to do and then you will be able to choose when to have the blur and when not to.
