### ISSUE TITLE
[Bug] Unable to add tokens via drag/drop or add token macro

### ISSUE THREAD

**Issue by MightyMushka** [CristianVasile23/conversation-hud#36]
Module Version: 5.3.0
System: PF2e (5.12.7)

Issue: Trying to add a token via the add token to conversation macro or via drag and drop does nothing. In the console, the attached screenshot shows the error being thrown which seems to be associated with not being able to read faction properties. However, if creating a conversation via the Pull actors in scene method, there seems to no issue adding them.
![Screenshot 2024-01-21 000328](https://github.com/CristianVasile23/conversation-hud/assets/155797771/95e64584-d8df-4be4-ae31-cefac0b0b21c)

**Comment by DiceKnights** [comment]
Same issue here since the latest patch. I can only add participants to conversation by dragging them to the scene and then using the new pull participants from scene function.

**Comment by CristianVasile23** [comment]
Yeah, that's on me. The way data is being handled changed a bit when adding the new faction sheet and apparently I made an oopsie and forgot to test the drag and drop functionality. Fixing the issue right now.

**Comment by CristianVasile23** [comment]
The issue has been fixed with release 5.3.1. If there is any other issue feel free to reach out and I will fix it as soon as possible.

**Comment by MightyMushka** [comment]
Cheers for such a quick fix! Much appreciated, and looks solved :)
