### ISSUE TITLE
[Feature Request] Option to Scale Image to bounding box

### ISSUE THREAD

**Issue by MightyMushka** [CristianVasile23/conversation-hud#37]
First off, the module is absolutely invaluable to my group as a way to represent conversations and focus the team. Thanks so much!

I utilise the Beastiary art pack from Paizo and the Kingmaker module, which provides a huge amount of art, all backgroundless. The dimensions for these though are not consistent due to different poses, etc. I'd love an option to scale the artwork in the active participant box to ensure it's all shown, scaling based on the largest dimension.

Regardless, thoroughly enjoy the module and it always has a place on the modules list!

**Comment by Mystler** [comment]
Looking at the CSS for the module, using the vertical Portrait Style setting, I found these quick and dirty hacks to the following files to produce a nice result. This can probably be implemented better as an additional setting in the module but it works for a temporary edit.

css/active-conversation/active-participant.css
- Line 113 in block `.conversation-hud-content .active-participant .portrait`:
  Change `object-fit` to `contain`.

css/active-conversation/module-settings.css
- Line 6 in block `.conversation-hud-content .active-participant.vertical`:
  Comment out / Remove `aspect-ratio` and put `max-height: 630px;`
- Lines 26 and 27 in block `conversation-hud-wrapper.minimized .conversation-hud-content .active-participant.vertical`:
  Change both `width` and `height` to `max-width` and `max-height` respectively.

**Comment by CristianVasile23** [comment]
That looks like a really good temporary workaround @Mystler, thanks for sharing it. Granted, the dimensions change for each portrait mode, but that will no longer be an issue as I have reworked the way images are displayed and you can now add padding as well as anchor each image both vertically and horizontally which should allow for much more flexibility. Update should be live sometimes towards the end of this week.
