### ISSUE TITLE
fr translation

### ISSUE THREAD

**Issue by MastaGooz** [CristianVasile23/conversation-hud#40]
Hi man, great module, I love it !

I did a french translation of the json file, would it be possible to add it?

[fr.json](https://github.com/CristianVasile23/conversation-hud/files/14043762/fr.json)

**Comment by CristianVasile23** [comment]
Hey there, and thank you so much for the contribution! I will gladly add the French translation to the next version of the module (though it might take a little while as I am a bit busy at the moment).

In the future, as new functionalities come out and text is added,  if you have the time to update the JSON, you can once again create a new issue with the updated translation or you can even create a pull request if you want to and I will merge it.

Either way, thank you for the translation I really appreciate it!

One small question however, when I credit you is it okay to use the GitHub username or would you like to be tagged another way?

**Comment by MastaGooz** [comment]
Hi ! 

I would be glad to keep up with the translation if you add something else yes.

You can credit me as my GitHub username yeah no problem.

Thanks for your work

**Comment by CristianVasile23** [comment]
Hey again and sorry for the long wait.

I will be adding the FR translation in the upcoming release which should happen this weekend, there are a couple of new features so I am attaching the new JSON, if you have the time you can look over the new fields and translate them as well. They are as follows:

- CHUD.strings
  - displayName
  - portraitScale
  - portraitAnchor
  - unknown
  - sceneConversationVisibilityOff

- CHUD.actions
  - displayName

- CHUD.settings
  - portraitAnchorVertical
  - portraitAnchorHorizontal
  - enableBlurToggle
  - blurAmount 

If you do not have the time to look over the new fields until the release, I will quickly patch them in after the translation is done.

[fr.json](https://github.com/CristianVasile23/conversation-hud/files/14696368/fr.json)

Thanks again for the work!
