### ISSUE TITLE
Start conversation with visibility "off"

### ISSUE THREAD

**Issue by this-gavagai** [CristianVasile23/conversation-hud#41]
Super cool module! I'm using it with a PF2e game I'm running with some younger kids to great effect. Thank you for sharing this work. It really adds a lot to our table.

I'm trying to understand if it is possible to save a conversation to start with visibility set to "off" at start. It is very handy to have scenes load on scene start, but sometimes those conversations shouldn't happen immediately when the scene loads. Is there any way to have the conversation ready but not yet visible on scene change?

**Comment by CristianVasile23** [comment]
Hey! Sadly at the moment there is no way to start the conversation with the visibility off, I hadn't thought of that, but that would be a really good addition and I will add this functionality to the next version of the module (an additional checkbox below the dropdown where you associate a conversation to the scene, checkbox which will determine if the conversation should be visible or not after the scene loads).

**Comment by this-gavagai** [comment]
Wow, that's awesome. Thanks so much for even considering it as a feature, and thanks again for your work. I'm really enjoying your module, and it has made a huge improvement to our table.

**Comment by CristianVasile23** [comment]
With release 5.4.0, there is now a checkbox beneath the scene conversation dropdown that, when checked, will start the conversation with its visibility off.

If there are any issues or questions, you can contact me and I will help as soon as possible.
