### ISSUE TITLE
Drag from one conversation to another?

### ISSUE THREAD

**Issue by PapaXilion** [CristianVasile23/conversation-hud#42]
Hey Cristian! Love your module!

I have a request; would it be possible to drag from one conversation to another? With all the prepwork on factions and whatnot, I am considering making one large 'cast' conversation, then drag who I need for a particular scenario into a new convo, and run it. For that, I'd need to be able to pull a participant from one list to another, including any registered faction.

Would that at all be possible? It would be an amazing Quality of Life improvement!

**Comment by PapaXilion** [comment]
I was thinking, being able to tie the faction registration to a token would suffice as well already, as I'd be able to make quick lists on the fly with that. But dragging would still have my preference.

**Comment by CristianVasile23** [comment]
Hey and sorry for the late reply. I haven't had time to look over CHUD the last couple of weeks.

That said, I have started work on the new update for the module and I will be adding support for participant drag and drop. This was an oversight from my part. I have no idea how I missed this when implementing drag and drop considering that you can drag and drop a conversation sheet into another one (and many other item types), but somehow I forgot to add the option to drag a participant from a sheet to another one.

Rest assured, this is a very easy addition and I will be adding this feature to the next version of the module coming sometime in the next couple of weeks.

In the meantime, as a workaround, you can create individual sheets for each actor and drag and drop them that way.

**Comment by CristianVasile23** [comment]
With release 5.4.0 you can now drag and drop participants from one conversation to another. This works on all drag and drop compatible elements (you can drag and drop a participant from the active conversation onto a sheet, etc.).

If there are any issues or questions, feel free to contact me and I will try to solve them as soon as possible.
