### ISSUE TITLE
[Feature Request] Possibility of adding video to Conversation Hud

### ISSUE THREAD

**Issue by Angelixus** [CristianVasile23/conversation-hud#43]
As of now, looking at the conversation-hud templates, the conversation hud module only allows for `<img>` tags to be created and set for any given conversation. It would be great if we could add videos with the `<video>` tag to any conversation.

We of course can circumvent this with animated `webp` but it is cumbersome to use when you could just add a mp4 file.

I see that the template allows for conditional statements, we could add a conditional statement like `{{#if isVideo}}`. The only problem would be to actually detect whether the given file is a video or not. Moreover, I think the best implementation would be for the video to have the `autoplay`, `muted` and `loop` flags.

PD: Thanks for the module, all DMs in my group (me included ofc) use it and its great

**Comment by CristianVasile23** [comment]
Hey there and sorry for the late reply.

I will be looking into this feature but I cannot promise anything yet. Although adding support for the <video> tag itself would be easy, there might be some technical limitations that might cause issues (I am mostly concerned about various edge cases that could appear). In theory, it should be possible and not too hard. But I need to look into it.

If it's something that can be added easily, I will add support in the next version of the module. If it's something more complex, it might come in a later version of the module (that is if it's doable, if not I will let you know as soon as possible).

**Comment by CristianVasile23** [comment]
With release 5.4.0, you can now use video files for participant portraits. The currently supported video formats are as follows: .mpg, .mp2, .mpeg, .mpe, .mpv, and .mp4. If there are any other formats that you might be using and I have missed, feel free to tell me.

Furthermore, if you have any other questions or issue, feel free to reach out and I will answer as soon as possible.
