### ISSUE TITLE
Allow setting on actor conversation data like faction, portrait alignment etc.

### ISSUE THREAD

**Issue by adriangaro** [CristianVasile23/conversation-hud#50]
At the current moment to be able to easily drag and drop an NPC into the conversation and have everything configured requires one to make conversation with only one participant for said NPC.

If you could configure this information in the token prototype or somewhere else so whenever the actor is dragged in conversation that information is automatically filled and you no longer need to create as much boilerplate.

**Comment by adriangaro** [comment]
Probably storing on token/prototype would have the advantage of being able to be used better with the pull from scene functionality.

**Comment by adriangaro** [comment]
Additionally there could be a flag on token if it should be pulled from scene, allowing tokens that might not represent an actor/NPC proper to not appear in the list you choose from.

**Comment by adriangaro** [comment]
If a conversation participant has a token/actor attached, it would also be nice to be able to double click the image to open the actor sheet for example.

**Comment by CristianVasile23** [comment]
Hey there and sorry for the late reply. Was quite busy, only now getting back on working on the module.

Regarding your suggestions, what I aim to do and it has been something that I have been planning to do for a while is to allow users to link a conversation sheet to a token. There are a couple of reasons why I do not really want to add all the participant configuration settings to the tokens themselves.

The main reason is that it is much simpler to just associate a conversation to a token. I think that adding all the configuration fields inside the token config would add further complexity to an already complex sheet. Furthermore, doing so might also cause conflicts with other modules that also edit that config screen as well. As such, I want to keep the alterations to a minimum.

Another reason as to why I want to do the linking is to enable users to possibly associate multiple participants to a single token. I think there are possible cases where you would want to have multiple conversation participants linked to a single token (a token representing a mob for example). To do this, once again, the easiest way is to simply link an already existing conversation sheet to a token.

The need for the boilerplate is a bit frustrating I get it, but ConversationHUD was designed to also support participants that have no actor associated, and in order for this to happen, the conversation sheets need to be created. That said, I think linking actors to conversation sheets is the best solution that satisfies both worlds.

Regarding the rest of the suggestions, I will be adding a toggle to exclude tokens from being pulled from the scene, as well as a way to quickly access the actor sheet via the conversation controls.

**Comment by CristianVasile23** [comment]
With version 5.6.0, you can now associate conversations to tokens which will then be used when pulling said token from the scene. As mentioned before, while this does require a bit more prep work, it is a more universal solution that covers a lot of possible scenarios. 

On top of that, there has been a rework of the pull actors from scene which now allows you to edit the data that was pulled before adding the participants to the conversation. Furthermore, there is also a toggle which you can sue to exclude actors from being pulled into a conversation. And finally, there is also a new feature that allows conversation participants to have a linked actor which will then allow you to see the character sheet. This linking is done automatically when pulling actors from a scene.

If you have any other questions or issues, please feel free to reach out and I will do my best to help.
