### ISSUE TITLE
When a converstaion is made not visible to player When it is made visible again option to select no participant not last shown. 

### ISSUE THREAD

**Issue by AxiumDND** [CristianVasile23/conversation-hud#56]
Not a bug but an enhancment after using the module for a while.

I tend to set one converation up as all my NPCS i might need that session.  (when there talking to the NPCS there shown from conversation hud. 

When the players finish the scene I toggle the visibilty off then they go to a new scene and talk to a new NPC it would be better if on toggle visibilty on the no participent is shown until i select who they are talking to instead of the last NPC.

**Comment by CristianVasile23** [comment]
Yeah, I can do that. I can add a toggle in the settings so that whenever the visibility is toggled off then it will clear the active participant. It's not a huge task, I might add it by the end of the day with the bug fix in #57, or at least I hope so =))

**Comment by AxiumDND** [comment]
Saw this update last night working perfectly and exactly what was needed thankyou for your efforts module is so dam helpful in my games.
