### ISSUE TITLE
Conversation HUD Compendium is empty

### ISSUE THREAD

**Issue by Celldweller** [CristianVasile23/conversation-hud#61]
As shown in https://youtu.be/I7-tWP2puU0?si=narXdxl6rS3eKXtY&t=54 the ConversationHUD Macros Compendium should contain some documents but it is missing here:

![CleanShot 2024-07-04 at 15 53 15@2x](https://github.com/CristianVasile23/conversation-hud/assets/1809369/c66a069f-a093-494b-adfd-04f93059037d)

Installed Version 5.6.1 
Foundry  v12 Stable 4 (Build 327)

**Comment by warhammering** [comment]
I am having the same issue in Foundry Version 11. 
Installed version 5.6.1

**Comment by CristianVasile23** [comment]
Yes, this appears to be a bug. I have been able to reproduce this issue but I do not know why it is happening as the macros themselves should appear. I am looking into it and hopefully I will find a fix soon. Thanks for bringing this up to my attention.

**Comment by CristianVasile23** [comment]
Sorry for the long wait. I am happy to announce that with version 5.6.2, the macro compendium should no longer be empty. I will close the issue now, but if you encounter any problems feel free to reach out and I will help as soon as possible.
