### ISSUE TITLE
Hidden display name is shown as tooltip with Firefox

### ISSUE THREAD

**Issue by Celldweller** [CristianVasile23/conversation-hud#64]
Tested with Firefox 129.0b4
Conversation HUD 5.6.1

If you go to the tile of an NPC in Firefox whose name should remain hidden, the name still appears as a tooltip.

See picture:
![CleanShot 2024-07-17 at 17 50 55@2x](https://github.com/user-attachments/assets/2da35347-cf99-42b3-9fd5-9cb04b84b853)

**Comment by CristianVasile23** [comment]
Hey, thanks for reporting this bug. I will fix it and release an update in the following days, so stay tuned for that.

**Comment by CristianVasile23** [comment]
This issue should no longer appear in version 5.6.2. I will close the issue, but if the issue still persists or you find any other problems, feel free to reach out and I will do my best to help.
