### ISSUE TITLE
Scene configuration disappeared

### ISSUE THREAD

**Issue by Celldweller** [CristianVasile23/conversation-hud#65]
Conversation HUD 5.6.1
Chrome 126.0.6478.127

In the Ambience tab of the Scene Configuration, the settings for Conversation HUD have disappeared. It is therefore no longer possible to link a Scene to a Conversation.

Example:
![CleanShot 2024-07-17 at 17 58 33@2x](https://github.com/user-attachments/assets/8a23bd07-5ac9-4873-8eaa-d8d5aa991ecb)

**Comment by CristianVasile23** [comment]
Yes, I know about this issue. It's a problem with V12 since the ambience tab has been changed and thus the scene conversation inputs are no longer rendered correctly. I will also fix this in the following days, I haven't had the time until now but it's an easy fix and it shouldn't take too long.

**Comment by CristianVasile23** [comment]
I have fixed the issue in version 5.6.2. The scene conversation setting should render properly now. If there is anything I can help you with, feel free to reach out and like I said I will help as soon as possible.
