### ISSUE TITLE
[Enhancement] Companion Macros

### ISSUE THREAD

**Issue by harrisog** [CristianVasile23/conversation-hud#7]
Wishlist:

- A macro to mimic the behavior of the canvas controls button, i.e. toggles the HUD off if there is an active conversation, or opens a new Create Conversation dialog if not

- A macro to toggle the conversation state of a selected array of tokens via their linked actors, bypassing the Create Conversation dialog if there is no active conversation

**Comment by CristianVasile23** [comment]
This should be doable, I will be looking into it but it might take some time until I get around to it.

Regarding the conversation toggle macro with an array of tokens, do you mean a macro that adds all the currently selected tokens from a map into a conversation? Is this what you envisioned?

**Comment by harrisog** [comment]
> Regarding the conversation toggle macro with an array of tokens, do you mean a macro that adds all the currently selected tokens from a map into a conversation? Is this what you envisioned?

Yep, pretty much. Would probably be a good idea (and maybe not just for this use case) to use Token Names for participants to allow differentiating multiple NPC tokens linking back to the same actor.

**Comment by CristianVasile23** [comment]
As of release 3.5.0, the module comes with some examples macros which showcase ways to programmatically interact with the module. The packed macros should cover most of the functionality that you requested, but if there are some things that you might need, you can contact me and we can figure something out.

In the future and when I will have some time, I will also create a wiki that will detail the module API and how to use it to create macros.
