### ISSUE TITLE
Actor is not linked when adding by drag and drop

### ISSUE THREAD

**Issue by Celldweller** [CristianVasile23/conversation-hud#70]
If you use the “Pull participants from scene” function to add action actors to the scene via the tokens, they are automatically linked to the actor (icon is displayed next to the portrait). 
However, if you add an actor via drag and drop, the link is not created.

If you create a participant via an actor, a link should always be created.

**Comment by CristianVasile23** [comment]
Thanks for letting me know. This is an omission from my part, I will fix it as soon as possible and push out a release with the fix.

**Comment by CristianVasile23** [comment]
The issue should be fixed with release 5.6.3. Do let me know if there are any other problems and I will help as soon as I can. Thanks!
