### ISSUE TITLE
Insufficient User Rights.

### ISSUE THREAD

**Issue by lockiandd** [CristianVasile23/conversation-hud#75]
I am getting an error on the client side after setting up a scene with an associated conversation. Here are the steps to replicate my setup.

1. Create a conversation with at least one character and some art
2. Save this conversation to a journal entry
3. Associate the journal entry to the Scene Conversation parameter and use the Visibility Off flag.
4. Leave the scene and return - the client side instance will complain with an error : "Insufficient User Rights."

This does not seem to stop the functionality of ConversationHUD in anyway but it breaks immersion as my players notify me it's occurred. Happy to provide more information if required.

**Comment by CristianVasile23** [comment]
Hey there, thanks for bringing this up to my attention. I will push a fix as soon as possible as I have identified the cause of the issue. Thanks!
