### ISSUE TITLE
[Feature Request] Expose some CSS options

### ISSUE THREAD

**Issue by dirusulixes** [CristianVasile23/conversation-hud#9]
The module is great but I'd love for it to have some flexibility in the CSS exposed as settings. For example, I use square portraits in my campaign and wanted to have the active participant name font size a little bigger.
![Screenshot from 2023-04-13 11-22-56](https://user-images.githubusercontent.com/5693623/231734177-3c242e3f-66e7-4262-9767-ab143635f54c.png)

**Comment by CristianVasile23** [comment]
I will most likely add some options to customize some aspects of the HUD in the future, but it might take some time as this feature is not exactly a priority at the moment. That said, I will be looking into this eventually but I can't promise when that will be.

**Comment by Steelskinz** [comment]
I can't wait to see it,  would be great for swapping background picture when narrating :) 
![image](https://user-images.githubusercontent.com/93941729/234141126-6de784ff-79d8-47ce-b8d9-9119fec4f887.png)

**Comment by CristianVasile23** [comment]
Hey @Steelskinz, sorry for the late reply I have been a bit busy. By swapping the background picture, do you mean to have the option to change the dark overlay with a specific image? Or are you referring to something else?

**Comment by dirusulixes** [comment]
Nice, thanks! And yeah, square portraits weren't working properly. I modified the css to make them work.

**Comment by Steelskinz** [comment]
> Hey @Steelskinz, sorry for the late reply I have been a bit busy. By swapping the background picture, do you mean to have the option to change the dark overlay with a specific image? Or are you referring to something else?

I completly miss that notification (Sorry), I was more thinking changing the ratio of the picture so it can be use for a Theater of Mind Background.
